"""
This type stub file was generated by pyright.
"""

from slovnet import Morph as SlovnetMorph
from natasha.record import Record

class MorphToken(Record):
    __attributes__ = ...


class MorphMarkup(Record):
    __attributes__ = ...
    def print(self): # -> None:
        ...
    


def adapt_tokens(tokens): # -> Generator[MorphToken, Any, None]:
    ...

def adapt_markup(markup): # -> MorphMarkup:
    ...

def format_tag(pos, feats): # -> LiteralString:
    ...

def format_markup(markup, size=...): # -> Generator[LiteralString, Any, None]:
    ...

def print_markup(markup): # -> None:
    ...

class MorphTagger(SlovnetMorph):
    def __init__(self, emb, path) -> None:
        ...
    
    def map(self, items): # -> Generator[MorphMarkup, Any, None]:
        ...
    


class NewsMorphTagger(MorphTagger):
    def __init__(self, emb, path=...) -> None:
        ...
    


