"""
This type stub file was generated by pyright.
"""

"""
cachefile.py - file with classes handling cached TLDs (e.g. downloads, updates)

.. Licence MIT
.. codeauthor:: Jan Lipovský <janlipovsky@gmail.com>, janlipovsky.cz
.. contributors: https://github.com/lipoja/URLExtract/graphs/contributors
"""
class CacheFileError(Exception):
    """Raised when some error occurred regarding file with cached TLDs."""
    ...


class CacheFile:
    """Class for working with cached TLDs in file."""
    _CACHE_FILE_NAME = ...
    _DATA_DIR = ...
    _URLEXTRACT_NAME = ...
    def __init__(self, cache_dir=...) -> None:
        """
        :param str cache_dir: base path for TLD cache, defaults to data dir
        :raises: CacheFileError when cached file is not readable for user
        """
        ...
    


