"""
This type stub file was generated by pyright.
"""

from .const import LOC, ORG, PER
from .segment import Segmenter
from .morph.vocab import MorphVocab
from .emb import NewsEmbedding
from .morph.tagger import NewsMorphTagger
from .syntax import NewsSyntaxParser
from .ner import NewsNERTagger
from .extractors import AddrExtractor, DatesExtractor, MoneyExtractor, NamesExtractor
from .doc import Doc

