"""
This type stub file was generated by pyright.
"""

from navec import Navec

class Embedding(Navec):
    def __init__(self, path) -> None:
        ...
    


class NewsEmbedding(Embedding):
    def __init__(self, path=...) -> None:
        ...
    


