"""
This type stub file was generated by pyright.
"""

from yargy import Parser as YargyParser
from .record import Record

class Parser(YargyParser):
    def __init__(self, rule, morph) -> None:
        ...
    


class Match(Record):
    __attributes__ = ...


def adapt_match(match): # -> Match:
    ...

class Extractor:
    def __init__(self, rule, morph) -> None:
        ...
    
    def __call__(self, text): # -> Generator[Match, Any, None]:
        ...
    
    def find(self, text): # -> Match | None:
        ...
    


class NamesExtractor(Extractor):
    def __init__(self, morph) -> None:
        ...
    


class DatesExtractor(Extractor):
    def __init__(self, morph) -> None:
        ...
    


class MoneyExtractor(Extractor):
    def __init__(self, morph) -> None:
        ...
    


class AddrExtractor(Extractor):
    def __init__(self, morph) -> None:
        ...
    
    def find(self, text): # -> Match | None:
        ...
    


