"""
This type stub file was generated by pyright.
"""

from slovnet import NER as SlovnetNER
from .record import Record

class NERMarkup(Record):
    __attributes__ = ...
    def print(self): # -> None:
        ...
    


def adapt_spans(spans): # -> Generator[Span, Any, None]:
    ...

def adapt_markup(markup): # -> NERMarkup:
    ...

class NERTagger(SlovnetNER):
    def __init__(self, emb, path) -> None:
        ...
    
    def map(self, items): # -> Generator[NERMarkup, Any, None]:
        ...
    


class NewsNERTagger(NERTagger):
    def __init__(self, emb, path=...) -> None:
        ...
    


