"""
This type stub file was generated by pyright.
"""

from .record import Record

class Slot(Record):
    __attributes__ = ...


class Obj(Record):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    @property
    def slots(self): # -> Generator[Slot, Any, None]:
        ...
    


class Name(Obj):
    __attributes__ = ...


class Date(Obj):
    __attributes__ = ...


class Money(Obj):
    __attributes__ = ...


class AddrPart(Obj):
    __attributes__ = ...


class Addr(Obj):
    __attributes__ = ...


