"""
This type stub file was generated by pyright.
"""

def parse_annotation(annotation): # -> tuple[Any | type[str], bool, bool]:
    ...

class Record:
    __attributes__ = ...
    __annotations__ = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __ne__(self, other) -> bool:
        ...
    
    def __iter__(self): # -> Generator[Any, None, None]:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @property
    def as_json(self): # -> OrderedDict[Any, Any]:
        ...
    
    @classmethod
    def from_json(cls, data): # -> Self:
        ...
    


