"""
This type stub file was generated by pyright.
"""

from .record import Record

class Sent(Record):
    __attributes__ = ...


class Token(Record):
    __attributes__ = ...


def adapt_token(token): # -> Token:
    ...

def adapt_sent(sent): # -> Sent:
    ...

class Segmenter(Record):
    def tokenize(self, text): # -> Generator[Token, Any, None]:
        ...
    
    def sentenize(self, text): # -> Generator[Sent, Any, None]:
        ...
    


