"""
This type stub file was generated by pyright.
"""

from .record import Record

class Span(Record):
    __attributes__ = ...


def adapt_spans(spans): # -> Generator[Span, Any, None]:
    ...

def offset_spans(spans, offset): # -> Generator[Span, Any, None]:
    ...

def envelop_spans(spans, envelopes): # -> Generator[list[Any], Any, None]:
    ...

