"""
This type stub file was generated by pyright.
"""

from slovnet import Syntax as SlovnetSyntax
from .record import Record

class SyntaxToken(Record):
    __attributes__ = ...


class SyntaxMarkup(Record):
    __attributes__ = ...
    def print(self): # -> None:
        ...
    


def adapt_tokens(tokens): # -> Generator[SyntaxToken, Any, None]:
    ...

def adapt_markup(markup): # -> SyntaxMarkup:
    ...

def token_deps(tokens): # -> Generator[tuple[Any, Any, Any], Any, None]:
    ...

def markup_words(markup): # -> list[Any]:
    ...

def print_markup(markup): # -> None:
    ...

class SyntaxParser(SlovnetSyntax):
    def __init__(self, emb, path) -> None:
        ...
    
    def map(self, items): # -> Generator[SyntaxMarkup, Any, None]:
        ...
    


class NewsSyntaxParser(SyntaxParser):
    def __init__(self, emb, path=...) -> None:
        ...
    


